# Generated by Django 3.1.7 on 2021-04-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='author',
            field=models.CharField(default='Chaoping Xing', max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
