# Generated by Django 3.1.7 on 2021-04-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210405_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pub_date',
            field=models.IntegerField(default=2000),
        ),
    ]
