# Generated by Django 3.1.7 on 2021-04-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='filename',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
